### ISSUE TITLE
NestedField in NestedField empty array - related objects not added

### ISSUE THREAD

**Issue by benjaminkarskens** [Codoc-os/django-opensearch-dsl#25] opened 2022-08-25 13:33 UTC
I have a NestedField (jobs) within a NestedField (persons). The first NestedField (persons) works fine but the second (jobs) does not get populated when related objects are added. It seems like there is no Signal triggered after creation. 

```
Models.py
class CampaignSearch(models.Model):
    external_id = models.UUIDField(unique=True, default=uuid.uuid4)
    name = models.CharField(max_length=320, null=True, blank=True)

class Person(models.Model):
    external_id = models.UUIDField(unique=True, default=uuid.uuid4)
    first_name = models.CharField(max_length=320, null=True, blank=True)
    last_name = models.CharField(max_length=320, null=True, blank=True)
    campaign_search = models.ManyToManyField("CampaignSearch", related_name="persons", blank=True)

class Job(models.Model):
    company_name = models.CharField(max_length=650, null=True, blank=True)
    job_title = models.CharField(max_length=550, null=True, blank=True, db_index=True)
    person = models.ForeignKey(Person, related_name='jobs', on_delete=models.CASCADE)
```

```
documents.py
@registry.register_document
class CampaignSearchDocument(Document):

    persons = NestedField(properties={
        'first_name': KeywordField(),
        'last_name': KeywordField(),
        "jobs": NestedField(
            properties={
                'company_name': KeywordField(),
                'job_title': KeywordField(), 
            })
    })

    class Index:
        name = 'campaign_search'  
        settings = {  
            'number_of_shards': 1,
            'number_of_replicas': 1
        }
  
    class Django:
        model = CampaignSearch  # The model associated with this Document
        queryset_pagination = 5000

        fields = [  
            'external_id',
            'name',
        ]

```

When I update the Document Index the related field (jobs) do get added but also a new empty CampaignSearch object is created in the Index. 

`CampaignSearchDocument().update(thing=campaign_search, action="index")
`

**Comment by qcoumes** [comment] 2022-09-09 12:28
I could not reproduce the error, can you send a minimal example project (git or zip) ?

**Comment by qcoumes** [comment] 2022-11-19 19:11
Closing since I could not reproduce the bug on no minimal reproducible example where provided.

**Closed by qcoumes** 2022-11-19 19:11 UTC
Labels: bug, question
